import { Hackathon, PrizeCategory } from "../shared/contracts";

interface SeedRecord {
  id: string;
  title: string;
  url: string;
  sourcePlatform: string;
  format: Hackathon["format"];
  locationText: string;
  coordinates?: Hackathon["coordinates"];
  startOffsetDays: number;
  finalOffsetDays: number;
  themes: string[];
  organizerPastEvents: number;
  prizes: PrizeCategory[];
  createdOffsetDays: number;
}

const DAY_IN_MS = 24 * 60 * 60 * 1000;

const addDays = (baseDate: Date, offsetDays: number): string =>
  new Date(baseDate.getTime() + offsetDays * DAY_IN_MS).toISOString();

const SEED_RECORDS: SeedRecord[] = [
  {
    id: "seed-001",
    title: "Global AI Hackathon 2026",
    url: "https://devpost.com/hackathons",
    sourcePlatform: "Devpost",
    format: "Online",
    locationText: "Global",
    startOffsetDays: 1,
    finalOffsetDays: 3,
    themes: ["AI/ML", "Open Source"],
    organizerPastEvents: 7,
    prizes: ["Cash", "Swag"],
    createdOffsetDays: -1,
  },
  {
    id: "seed-002",
    title: "Delhi NCR Web3 Sprint",
    url: "https://devfolio.co/hackathons",
    sourcePlatform: "Devfolio",
    format: "Offline",
    locationText: "Gurugram, Haryana",
    coordinates: { lat: 28.4595, lng: 77.0266 },
    startOffsetDays: 2,
    finalOffsetDays: 4,
    themes: ["Web3", "Blockchain"],
    organizerPastEvents: 2,
    prizes: ["Cash"],
    createdOffsetDays: -2,
  },
  {
    id: "seed-003",
    title: "Bangalore Open Source Weekend",
    url: "https://www.hackerearth.com/challenges/",
    sourcePlatform: "HackerEarth",
    format: "Offline",
    locationText: "Bengaluru, Karnataka",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    startOffsetDays: 5,
    finalOffsetDays: 8,
    themes: ["Open Source", "Beginner-friendly"],
    organizerPastEvents: 11,
    prizes: ["Job/Internship", "Swag"],
    createdOffsetDays: -3,
  },
  {
    id: "seed-004",
    title: "Healthcare Innovators Hybrid",
    url: "https://mlh.io/seasons/2026/events",
    sourcePlatform: "MLH",
    format: "Hybrid",
    locationText: "New Delhi, Delhi",
    coordinates: { lat: 28.6139, lng: 77.209 },
    startOffsetDays: 7,
    finalOffsetDays: 35,
    themes: ["Healthcare", "AI/ML"],
    organizerPastEvents: 4,
    prizes: ["Cash", "Job/Internship"],
    createdOffsetDays: -3,
  },
  {
    id: "seed-005",
    title: "Noida AI Builders",
    url: "https://devfolio.co/hackathons",
    sourcePlatform: "Devfolio",
    format: "Offline",
    locationText: "Noida, Uttar Pradesh",
    coordinates: { lat: 28.5355, lng: 77.391 },
    startOffsetDays: 0,
    finalOffsetDays: 2,
    themes: ["AI/ML"],
    organizerPastEvents: 6,
    prizes: ["Cash", "Swag"],
    createdOffsetDays: -1,
  },
  {
    id: "seed-006",
    title: "Global Game Jam Online",
    url: "https://itch.io/jams",
    sourcePlatform: "Itch.io",
    format: "Online",
    locationText: "Global",
    startOffsetDays: -1,
    finalOffsetDays: 1,
    themes: ["Gaming", "Beginner-friendly"],
    organizerPastEvents: 15,
    prizes: ["Unspecified"],
    createdOffsetDays: -4,
  },
  {
    id: "seed-007",
    title: "SF Bay Area FinTech Hack",
    url: "https://devpost.com/hackathons",
    sourcePlatform: "Devpost",
    format: "Offline",
    locationText: "San Francisco, California",
    coordinates: { lat: 37.7749, lng: -122.4194 },
    startOffsetDays: 4,
    finalOffsetDays: 11,
    themes: ["FinTech", "Web3"],
    organizerPastEvents: 1,
    prizes: ["Cash"],
    createdOffsetDays: -2,
  },
  {
    id: "seed-008",
    title: "London Climate Tech Challenge",
    url: "https://devfolio.co/hackathons",
    sourcePlatform: "Devfolio",
    format: "Hybrid",
    locationText: "London, UK",
    coordinates: { lat: 51.5074, lng: -0.1278 },
    startOffsetDays: 12,
    finalOffsetDays: 42,
    themes: ["Climate", "Hardware"],
    organizerPastEvents: 3,
    prizes: ["Cash", "Swag"],
    createdOffsetDays: -5,
  },
  {
    id: "seed-009",
    title: "Remote Open Source Infra Jam",
    url: "https://devpost.com/hackathons",
    sourcePlatform: "Devpost",
    format: "Online",
    locationText: "Global",
    startOffsetDays: 3,
    finalOffsetDays: 10,
    themes: ["Open Source", "Cloud"],
    organizerPastEvents: 9,
    prizes: ["Job/Internship"],
    createdOffsetDays: -2,
  },
  {
    id: "seed-010",
    title: "Mumbai HealthTech Buildathon",
    url: "https://www.hackerearth.com/challenges/",
    sourcePlatform: "HackerEarth",
    format: "Offline",
    locationText: "Mumbai, Maharashtra",
    coordinates: { lat: 19.076, lng: 72.8777 },
    startOffsetDays: 9,
    finalOffsetDays: 14,
    themes: ["Healthcare", "AI/ML"],
    organizerPastEvents: 0,
    prizes: ["Cash", "Unspecified"],
    createdOffsetDays: -1,
  },
  {
    id: "seed-011",
    title: "Global Web3 Governance Hack",
    url: "https://devpost.com/hackathons",
    sourcePlatform: "Devpost",
    format: "Online",
    locationText: "Global",
    startOffsetDays: 6,
    finalOffsetDays: 36,
    themes: ["Web3", "Policy"],
    organizerPastEvents: 4,
    prizes: ["Cash", "Swag"],
    createdOffsetDays: -3,
  },
  {
    id: "seed-012",
    title: "Pune Beginners Build Sprint",
    url: "https://www.hackerearth.com/challenges/",
    sourcePlatform: "HackerEarth",
    format: "Offline",
    locationText: "Pune, Maharashtra",
    coordinates: { lat: 18.5204, lng: 73.8567 },
    startOffsetDays: 1,
    finalOffsetDays: 2,
    themes: ["Beginner-friendly", "Open Source"],
    organizerPastEvents: 0,
    prizes: ["Swag"],
    createdOffsetDays: -1,
  },
];

export const createSeedHackathons = (baseDate: Date = new Date()): Hackathon[] =>
  SEED_RECORDS.map((record) => ({
    id: record.id,
    title: record.title,
    url: record.url,
    sourcePlatform: record.sourcePlatform,
    format: record.format,
    locationText: record.locationText,
    coordinates: record.coordinates,
    startDate: addDays(baseDate, record.startOffsetDays),
    finalSubmissionDate: addDays(baseDate, record.finalOffsetDays),
    daysToFinal: Math.max(0, record.finalOffsetDays - record.startOffsetDays),
    themes: record.themes,
    organizerPastEvents: record.organizerPastEvents,
    prizes: record.prizes,
    createdAt: addDays(baseDate, record.createdOffsetDays),
  }));
